# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcHEAD(wx.Frame):
#!XRCED:begin-block:xrcHEAD.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcHEAD.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "HEAD")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    EMA_startup_window_xrc = '''\
<?xml version="1.0" ?>
<resource>
  <object class="wxFrame" name="HEAD">
    <object class="wxMenuBar" name="MEN_BAR"/>
    <object class="wxToolBar">
      <object class="wxButton" name="BTN_OUTPUT">
        <label>Select output file</label>
        <style>wxNO_BORDER</style>
        <bg>#80FF80</bg>
      </object>
      <object class="wxButton" name="BTN_RUN">
        <label>Run script</label>
        <style>wxBU_EXACTFIT|wxNO_BORDER</style>
        <bg>#FF8080</bg>
        <enabled>1</enabled>
      </object>
    </object>
    <object class="wxBoxSizer">
      <object class="sizeritem">
        <object class="wxStaticLine">
          <style>wxLI_HORIZONTAL</style>
        </object>
        <flag>wxEXPAND</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxBoxSizer">
            <orient>wxVERTICAL</orient>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <object class="sizeritem">
                  <object class="wxStaticText">
                    <label>Data output filename:</label>
                    <style>wxALIGN_LEFT</style>
                  </object>
                  <flag>wxALIGN_LEFT</flag>
                </object>
                <object class="sizeritem">
                  <object class="wxTextCtrl" name="TXT_FILENAME">
                    <value>&lt;choose the filename with button&gt;</value>
                    <style>wxTE_READONLY</style>
                  </object>
                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
                  <minsize>350,20</minsize>
                </object>
                <orient>wxHORIZONTAL</orient>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <orient>wxHORIZONTAL</orient>
                <object class="sizeritem">
                  <object class="wxStaticText">
                    <label>Working directory:</label>
                  </object>
                </object>
                <object class="sizeritem">
                  <object class="wxTextCtrl" name="TXT_DIRECTORY">
                    <value>&lt;choose the filename with button&gt;</value>
                    <style>wxTE_READONLY</style>
                  </object>
                  <flag>wxALL|wxEXPAND|wxGROW|wxALIGN_LEFT|wxADJUST_MINSIZE</flag>
                  <minsize>350,20</minsize>
                </object>
              </object>
            </object>
          </object>
        </object>
      </object>
      <object class="sizeritem">
        <object class="wxStaticLine"/>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="PNL_SCRIPT_SELECT">
          <object class="wxBoxSizer">
            <orient>wxHORIZONTAL</orient>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxStaticText" name="TXT_CATEGORIES">
                    <label>Categories of scripts</label>
                  </object>
                </object>
                <object class="sizeritem">
                  <object class="wxListCtrl" name="LST_CATEGORIES">
                    <size>250,100</size>
                    <style>wxLC_LIST|wxLC_SINGLE_SEL|wxLC_VRULES</style>
                  </object>
                </object>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxBoxSizer">
                <orient>wxVERTICAL</orient>
                <object class="sizeritem">
                  <object class="wxStaticText" name="TXT_SCRIPTS">
                    <label>Select testing script</label>
                  </object>
                </object>
                <object class="sizeritem">
                  <object class="wxListCtrl" name="LST_SCRIPTS">
                    <size>250,100</size>
                    <style>wxLC_LIST|wxLC_SINGLE_SEL|wxLC_VRULES</style>
                  </object>
                </object>
              </object>
            </object>
          </object>
        </object>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="PNL_PARAM_EDIT">
          <style/>
        </object>
        <flag>wxTOP|wxALL|wxEXPAND|wxGROW</flag>
      </object>
      <object class="sizeritem">
        <object class="wxTextCtrl" name="TXT_DESRIPTION">
          <size>500,200</size>
          <style>wxTE_AUTO_SCROLL|wxTE_MULTILINE|wxTE_READONLY|wxTE_WORDWRAP</style>
        </object>
        <flag>wxALL|wxEXPAND|wxGROW</flag>
      </object>
      <orient>wxVERTICAL</orient>
    </object>
    <size>500,500</size>
    <title>EMA - Electrical measurement apparate control</title>
    <centered>1</centered>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/EMA_startup_window/EMA_startup_window_xrc', EMA_startup_window_xrc)
    __res.Load('memory:XRC/EMA_startup_window/EMA_startup_window_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Select output file")
    _("Run script")
    _("Data output filename:")
    _("<choose the filename with button>")
    _("Working directory:")
    _("<choose the filename with button>")
    _("Categories of scripts")
    _("Select testing script")
    _("EMA - Electrical measurement apparate control")

