# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcBANANA(wx.Frame):
#!XRCED:begin-block:xrcBANANA.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcBANANA.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "BANANA")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    ControlFrameCELIV_xrc = '''\
<?xml version="1.0" ?>
<resource>
  <object class="wxFrame" name="BANANA">
    
    <object class="wxMenuBar" name="MEN_BAR"/>
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxFlexGridSizer">
            <object class="sizeritem">
              <object class="wxStaticText">
                <label>Data filename:</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxTextCtrl" name="TXT_FILENAME"/>
              <flag>wxEXPAND|wxGROW</flag>
            </object>
            <object class="sizeritem">
              <object class="wxStaticText">
                <label>Data directory:</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxTextCtrl" name="TXT_DIRECTORY"/>
              <flag>wxEXPAND</flag>
            </object>
            <cols>2</cols>
            <rows>2</rows>
            <hgap>10</hgap>
            <growablecols>1</growablecols>
            <growablerows>1,2</growablerows>
          </object>
        </object>
        <flag>wxEXPAND|wxGROW</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel">
          <object class="wxBoxSizer">
            <object class="sizeritem">
              <object class="wxButton" name="BTN_OUTPUT">
                <label>OUTPUT</label>
                <fg>#FF0000</fg>
                <font>
                  <size>10</size>
                  <style>normal</style>
                  <weight>bold</weight>
                  <underlined>0</underlined>
                  <family>swiss</family>
                  <face>Tahoma</face>
                  <encoding>WINDOWS-1250</encoding>
                </font>
              </object>
              <flag>wxEXPAND|wxGROW</flag>
            </object>
            <object class="spacer">
              <size>10</size>
            </object>
            <object class="sizeritem">
              <object class="wxButton" name="BTN_RECORD">
                <label>RECORD Scope</label>
                <fg>#FF0000</fg>
                <font>
                  <size>8</size>
                  <style>normal</style>
                  <weight>bold</weight>
                  <underlined>0</underlined>
                  <family>swiss</family>
                  <face>Tahoma</face>
                  <encoding>WINDOWS-1250</encoding>
                </font>
              </object>
            </object>
            <object class="spacer">
              <size>10</size>
            </object>
            <orient>wxHORIZONTAL</orient>
            <object class="sizeritem">
              <object class="wxStaticText">
                <label>amount:</label>
              </object>
            </object>
            <object class="sizeritem">
              <object class="wxChoice" name="SCOPE_POINTS">
                <content>
                  <item>100</item>
                  <item>1000</item>
                  <item>10000</item>
                  <item>MAX</item>
                </content>
                <selection>1</selection>
              </object>
            </object>
          </object>
        </object>
        <flag>wxEXPAND|wxGROW</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="PNL_PARAM_EDIT"/>
        <flag>wxEXPAND|wxGROW</flag>
      </object>
      <object class="sizeritem">
        <object class="wxPanel" name="TRIGGER">
          <object class="wxBoxSizer">
            <orient>wxHORIZONTAL</orient>
            <object class="sizeritem">
              <object class="wxButton" name="BTN_SINGLE">
                <label>SINGLE shot</label>
                <style>wxDOUBLE_BORDER</style>
              </object>
            </object>
            <object class="spacer">
              <size>10</size>
              <option>0</option>
            </object>
            <object class="sizeritem">
              <object class="wxToggleButton" name="BTN_REPEAT">
                <label>... CONTINUOUS ...</label>
              </object>
              <flag>wxEXPAND|wxGROW</flag>
            </object>
          </object>
        </object>
        <flag>wxEXPAND|wxGROW</flag>
      </object>
      <object class="sizeritem">
        <object class="wxTextCtrl" name="TXT_DESCRIPTION">
          <style>wxTE_MULTILINE|wxHSCROLL|wxTE_WORDWRAP</style>
        </object>
        <flag>wxEXPAND|wxGROW</flag>
        <border>3</border>
        <minsize>200,200</minsize>
      </object>
    </object>
    <title>CELIV experiment control GUI</title>
    <style>wxDEFAULT_FRAME_STYLE|wxRESIZE_BORDER</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/ControlFrameCELIV/ControlFrameCELIV_xrc', ControlFrameCELIV_xrc)
    __res.Load('memory:XRC/ControlFrameCELIV/ControlFrameCELIV_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("Data filename:")
    _("Data directory:")
    _("OUTPUT")
    _("RECORD Scope")
    _("amount:")
    _("100")
    _("1000")
    _("10000")
    _("MAX")
    _("SINGLE shot")
    _("... CONTINUOUS ...")
    _("CELIV experiment control GUI")

